// Generated by gencpp from file robot_main/getMissionResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MAIN_MESSAGE_GETMISSIONRESPONSE_H
#define ROBOT_MAIN_MESSAGE_GETMISSIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_main
{
template <class ContainerAllocator>
struct getMissionResponse_
{
  typedef getMissionResponse_<ContainerAllocator> Type;

  getMissionResponse_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , action()
    , color()  {
    }
  getMissionResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , action(_alloc)
    , color(_alloc)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  _action_type action;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::robot_main::getMissionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_main::getMissionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct getMissionResponse_

typedef ::robot_main::getMissionResponse_<std::allocator<void> > getMissionResponse;

typedef boost::shared_ptr< ::robot_main::getMissionResponse > getMissionResponsePtr;
typedef boost::shared_ptr< ::robot_main::getMissionResponse const> getMissionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_main::getMissionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_main::getMissionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_main::getMissionResponse_<ContainerAllocator1> & lhs, const ::robot_main::getMissionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta &&
    lhs.action == rhs.action &&
    lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_main::getMissionResponse_<ContainerAllocator1> & lhs, const ::robot_main::getMissionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_main

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_main::getMissionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_main::getMissionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_main::getMissionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_main::getMissionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_main::getMissionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_main::getMissionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_main::getMissionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9881d38a4d072322f4f5f5870c50df7";
  }

  static const char* value(const ::robot_main::getMissionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9881d38a4d07232ULL;
  static const uint64_t static_value2 = 0x2f4f5f5870c50df7ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_main::getMissionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_main/getMissionResponse";
  }

  static const char* value(const ::robot_main::getMissionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_main::getMissionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 theta\n"
"string action\n"
"string color\n"
;
  }

  static const char* value(const ::robot_main::getMissionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_main::getMissionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.action);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getMissionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_main::getMissionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_main::getMissionResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MAIN_MESSAGE_GETMISSIONRESPONSE_H
