// Generated by gencpp from file robot_main/getMissionRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MAIN_MESSAGE_GETMISSIONREQUEST_H
#define ROBOT_MAIN_MESSAGE_GETMISSIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_main
{
template <class ContainerAllocator>
struct getMissionRequest_
{
  typedef getMissionRequest_<ContainerAllocator> Type;

  getMissionRequest_()
    : m_num(0)  {
    }
  getMissionRequest_(const ContainerAllocator& _alloc)
    : m_num(0)  {
  (void)_alloc;
    }



   typedef int32_t _m_num_type;
  _m_num_type m_num;





  typedef boost::shared_ptr< ::robot_main::getMissionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_main::getMissionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct getMissionRequest_

typedef ::robot_main::getMissionRequest_<std::allocator<void> > getMissionRequest;

typedef boost::shared_ptr< ::robot_main::getMissionRequest > getMissionRequestPtr;
typedef boost::shared_ptr< ::robot_main::getMissionRequest const> getMissionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_main::getMissionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_main::getMissionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_main::getMissionRequest_<ContainerAllocator1> & lhs, const ::robot_main::getMissionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.m_num == rhs.m_num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_main::getMissionRequest_<ContainerAllocator1> & lhs, const ::robot_main::getMissionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_main

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_main::getMissionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_main::getMissionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_main::getMissionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_main::getMissionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_main::getMissionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_main::getMissionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_main::getMissionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b1cfdcd647b5b0ea0c8ec63f1bb7d357";
  }

  static const char* value(const ::robot_main::getMissionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb1cfdcd647b5b0eaULL;
  static const uint64_t static_value2 = 0x0c8ec63f1bb7d357ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_main::getMissionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_main/getMissionRequest";
  }

  static const char* value(const ::robot_main::getMissionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_main::getMissionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 m_num\n"
;
  }

  static const char* value(const ::robot_main::getMissionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_main::getMissionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.m_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getMissionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_main::getMissionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_main::getMissionRequest_<ContainerAllocator>& v)
  {
    s << indent << "m_num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.m_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MAIN_MESSAGE_GETMISSIONREQUEST_H
