// Generated by gencpp from file robot_main/getMission.msg
// DO NOT EDIT!


#ifndef ROBOT_MAIN_MESSAGE_GETMISSION_H
#define ROBOT_MAIN_MESSAGE_GETMISSION_H

#include <ros/service_traits.h>


#include <robot_main/getMissionRequest.h>
#include <robot_main/getMissionResponse.h>


namespace robot_main
{

struct getMission
{

typedef getMissionRequest Request;
typedef getMissionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getMission
} // namespace robot_main


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_main::getMission > {
  static const char* value()
  {
    return "7992715a17ff2dfb6242bdc6efba1bfe";
  }

  static const char* value(const ::robot_main::getMission&) { return value(); }
};

template<>
struct DataType< ::robot_main::getMission > {
  static const char* value()
  {
    return "robot_main/getMission";
  }

  static const char* value(const ::robot_main::getMission&) { return value(); }
};


// service_traits::MD5Sum< ::robot_main::getMissionRequest> should match
// service_traits::MD5Sum< ::robot_main::getMission >
template<>
struct MD5Sum< ::robot_main::getMissionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_main::getMission >::value();
  }
  static const char* value(const ::robot_main::getMissionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_main::getMissionRequest> should match
// service_traits::DataType< ::robot_main::getMission >
template<>
struct DataType< ::robot_main::getMissionRequest>
{
  static const char* value()
  {
    return DataType< ::robot_main::getMission >::value();
  }
  static const char* value(const ::robot_main::getMissionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_main::getMissionResponse> should match
// service_traits::MD5Sum< ::robot_main::getMission >
template<>
struct MD5Sum< ::robot_main::getMissionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_main::getMission >::value();
  }
  static const char* value(const ::robot_main::getMissionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_main::getMissionResponse> should match
// service_traits::DataType< ::robot_main::getMission >
template<>
struct DataType< ::robot_main::getMissionResponse>
{
  static const char* value()
  {
    return DataType< ::robot_main::getMission >::value();
  }
  static const char* value(const ::robot_main::getMissionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MAIN_MESSAGE_GETMISSION_H
