// Generated by gencpp from file robot_arm/armCommand.msg
// DO NOT EDIT!


#ifndef ROBOT_ARM_MESSAGE_ARMCOMMAND_H
#define ROBOT_ARM_MESSAGE_ARMCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_arm
{
template <class ContainerAllocator>
struct armCommand_
{
  typedef armCommand_<ContainerAllocator> Type;

  armCommand_()
    : action()
    , color()  {
    }
  armCommand_(const ContainerAllocator& _alloc)
    : action(_alloc)
    , color(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  _action_type action;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::robot_arm::armCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_arm::armCommand_<ContainerAllocator> const> ConstPtr;

}; // struct armCommand_

typedef ::robot_arm::armCommand_<std::allocator<void> > armCommand;

typedef boost::shared_ptr< ::robot_arm::armCommand > armCommandPtr;
typedef boost::shared_ptr< ::robot_arm::armCommand const> armCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_arm::armCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_arm::armCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_arm::armCommand_<ContainerAllocator1> & lhs, const ::robot_arm::armCommand_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action &&
    lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_arm::armCommand_<ContainerAllocator1> & lhs, const ::robot_arm::armCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_arm::armCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_arm::armCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_arm::armCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_arm::armCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_arm::armCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_arm::armCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_arm::armCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b6b8ada7e9a5f60d947c18cb4bccc20";
  }

  static const char* value(const ::robot_arm::armCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b6b8ada7e9a5f60ULL;
  static const uint64_t static_value2 = 0xd947c18cb4bccc20ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_arm::armCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_arm/armCommand";
  }

  static const char* value(const ::robot_arm::armCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_arm::armCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string action\n"
"string color\n"
;
  }

  static const char* value(const ::robot_arm::armCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_arm::armCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct armCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_arm::armCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_arm::armCommand_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_ARM_MESSAGE_ARMCOMMAND_H
