// Generated by gencpp from file robot_arm/armState.msg
// DO NOT EDIT!


#ifndef ROBOT_ARM_MESSAGE_ARMSTATE_H
#define ROBOT_ARM_MESSAGE_ARMSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_arm
{
template <class ContainerAllocator>
struct armState_
{
  typedef armState_<ContainerAllocator> Type;

  armState_()
    : action()
    , situation()  {
    }
  armState_(const ContainerAllocator& _alloc)
    : action(_alloc)
    , situation(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  _action_type action;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _situation_type;
  _situation_type situation;





  typedef boost::shared_ptr< ::robot_arm::armState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_arm::armState_<ContainerAllocator> const> ConstPtr;

}; // struct armState_

typedef ::robot_arm::armState_<std::allocator<void> > armState;

typedef boost::shared_ptr< ::robot_arm::armState > armStatePtr;
typedef boost::shared_ptr< ::robot_arm::armState const> armStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_arm::armState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_arm::armState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_arm::armState_<ContainerAllocator1> & lhs, const ::robot_arm::armState_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action &&
    lhs.situation == rhs.situation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_arm::armState_<ContainerAllocator1> & lhs, const ::robot_arm::armState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_arm::armState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_arm::armState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_arm::armState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_arm::armState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_arm::armState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_arm::armState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_arm::armState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34e8372aba9fdf90a3e4bf2cfa63f7e3";
  }

  static const char* value(const ::robot_arm::armState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34e8372aba9fdf90ULL;
  static const uint64_t static_value2 = 0xa3e4bf2cfa63f7e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_arm::armState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_arm/armState";
  }

  static const char* value(const ::robot_arm::armState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_arm::armState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string action\n"
"string situation\n"
;
  }

  static const char* value(const ::robot_arm::armState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_arm::armState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.situation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct armState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_arm::armState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_arm::armState_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
    s << indent << "situation: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.situation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_ARM_MESSAGE_ARMSTATE_H
